- .gitignore
- Gemfile
- Gemfile.lock
- db/migrate/20211201024612_create_banks.rb
- db/schema.rb
- spec/rails_helper.rb
Added bank database from our setup task. Waiting to do Elevatorcos in case we need to make a column numeric.
> Add bank database

- bin/rails
Adding simplecov `if` statement to bin/rails
> Add simplecov to bin/rails

- Gemfile.lock
- db/migrate/20211201035724_create_elevatorcos.rb
- db/schema.rb
This PR includes:
ElevatorCos table migration
> Add elevatorcos database

- app/controllers/elevatorcos_controller.rb
- app/models/elevatorco.rb
- app/views/elevatorcos/index.html.erb
- config/routes.rb
- spec/features/elevatorcos/index_spec.rb
- spec/models/elevatorco_spec.rb
This PR includes: 
spec/features/elevatorcos/index_spec.rb 
- index content test  
spec/models/elevatorco_spec.rb 
- model test framework setup
config/routes.rb 
- elevatorco index route added 
app/views/elevatorcos/index.html.erb 
- basic html added to display names 
app/controllers/elevatorcos_controller.rb
- added index method 
app/models/elevatorco.rb
- added basic framework
> Feature test

- app/controllers/banks_controller.rb
- app/models/bank.rb
- app/views/banks/index.html.erb
- config/routes.rb
- spec/features/banks/index_spec.rb
- spec/models/bank_spec.rb
Added index method,` index_spec`, `index.html.erb`, and passed test
> Add bank index, index_spec & index.html

- app/controllers/banks_controller.rb
- app/views/banks/index.html.erb
- app/views/banks/show.html.erb
- config/routes.rb
- spec/features/banks/show_spec.rb
Created:
- `banks/show.html.erb`
- ` banks/show_spec.rb`
Updated: 
- 'banks_controller.rb' Added #show
- 'routes' Added `banks#show`
> Add banks#show

- app/controllers/elevatorcos_controller.rb
- app/views/elevatorcos/show.html.erb
- config/routes.rb
- spec/features/elevatorcos/show_spec.rb
PR includes: 
spec/features/elevatorcos/show_spec.rb 
- tests for show page 
app/config/routes.rb 
- added route for elevatorcos/show 
app/controllers/elevatorcos_controller.rb
- added method for show page 
app/views/elevatorcos/show.html.erb
- added layout for show page
> Elevatorcos Show/User Story 2

- app/controllers/branchs_controller.rb
- app/controllers/elevatorcos_controller.rb
- config/routes.rb
- db/migrate/20211201035724_create_elevatorcos.rb
- db/migrate/20211202210313_create_branchs.rb
- db/schema.rb
Added Branchs Migration
BranchsController
index file for branch
> Branch migrate

- app/controllers/buildings_controller.rb
- app/models/building.rb
- app/models/elevatorco.rb
- app/views/buildings/index.html.erb
- config/routes.rb
- db/migrate/20211202213829_create_buildings.rb
- db/migrate/20211202213907_add_elevatorco_to_buildings.rb
- db/schema.rb
- spec/features/buildings/index_spec.rb
- spec/models/building_spec.rb
- spec/models/elevatorco_spec.rb
PR includes: 
Migration: CreateBuildings
Migration: AddElevatorcoToBuildings
spec/features/buildings/index_spec.rb
- index test
spec/models/building_spec.rb
- shouldamatcher 
spec/models/elevatorco_spec.rb
- shouldamatcher
app/models/building.rb
- create model and add belongs_to association to elevatorco 
app/models/elevatorco.rb
- add has_many association to buildings 
app/controllers/buildings_controller.rb
- create file and add index method
app/config/routes.rb 
- add route to buildings index 
app/views/buildings/index.html.erb 
- create dir and index file, add layout for buildings index page
> Buildings index

- app/controllers/branches_controller.rb
- app/controllers/branchs_controller.rb
- app/models/branch.rb
- app/views/branches/index.html.erb
- db/migrate/20211202223837_create_branches.rb
- db/schema.rb
- spec/features/branches/index_spec.rb
Had to redo the migrations, turns out Rails can figure out Branch => Branches on its own, so Branchs wasn't working. Updated all the pertinent files and finished User Story 3.
> Changed User Story 3 to Branches, not Branchs

- app/controllers/branches_controller.rb
- app/models/bank.rb
- app/models/branch.rb
- app/views/branches/show.html.erb
- config/routes.rb
- db/migrate/20211202233105_remove_bank_id_from_branches.rb
- db/migrate/20211203001601_add_bank_to_branches.rb
- db/schema.rb
- db/seeds.rb
- spec/features/banks/show_spec.rb
- spec/features/branches/show_spec.rb
Created the branch#show for User Story 4.
Messed around a lot with the db, trying to fix migrations. Left behind old `branchs` path, should look into deleting that from schema later. Not causing any problems at the moment.
> Add branch show feature, fix some db errors

- app/controllers/buildings_controller.rb
- app/views/buildings/show.html.erb
- config/routes.rb
- db/schema.rb
- spec/features/buildings/show_spec.rb
PR includes: 
spec/features/buildings/show_spec.rb
- add tests (commented out date tests for now until we figure out formatting for them)
app/config/routes.rb
- added buildings show route
app/controllers/buildings_controller.rb 
- added show method 
app/views/buildings/show.html.erb
- added building show page layout
> Building show

- app/controllers/elevatorco_buildings_controller.rb
- app/views/elevatorco_buildings/index.html.erb
- config/routes.rb
- spec/features/elevatorcos/buildings/index_spec.rb
PR includes: 
spec/features/elevatorcos/buildings/index_spec.rb
- index test 
app/config/routes.rb 
- elevatorco buildings routing path
app/controllers/elevatorco_buildings_controller.rb
- new controller and index method
app/views/elevatorco_buildings.html.erb
- view page layout for elevator co and buildings
> Elevatorcos buildings

- Gemfile
- Gemfile.lock
- app/controllers/bank_branches_controller.rb
- app/views/bank_branches/index.html.erb
- config/routes.rb
- spec/features/banks/branches/index_spec.rb
- spec/models/bank_spec.rb
- spec/models/branch_spec.rb
- spec/rails_helper.rb
Create bank_branches#index
Added shoulda-matchers gem
User Story 5 complete
> Add bank_branches#index feature

- app/controllers/banks_controller.rb
- app/views/banks/index.html.erb
- spec/features/banks/index_spec.rb
- Finished User Story 6 for Banks
- Updated bank#index to order records by `created_at`
- Added tests to `banks/index_spec`
- Updated `banks/index.html`
> Add user story 6 to bank#index

- app/controllers/banks_controller.rb
- app/views/banks/index.html.erb
- app/views/banks/show.html.erb
- spec/features/banks/index_spec.rb
- spec/features/banks/show_spec.rb
Finished user story 7 for banks
Updated html file to include count of children
Added corresponding tests in show_spec
I chose to do it in html, I think one could also write a class method in the model for the same effect
> User story 7

- app/models/elevatorco.rb
- app/views/elevatorcos/show.html.erb
- spec/features/elevatorcos/show_spec.rb
- spec/models/elevatorco_spec.rb
PR includes: 
spec/models/elevatorco.rb 
- count_of_buildings method test 
spec/features/elevatorcos/show_spec.rb
- test for building count on page
app/models/elevatorco.rb
- add count_of_buildings method
app/views/elevatorcos/show.html.erb
- add building count to page display
> Num buildings

- app/models/bank.rb
- app/views/banks/show.html.erb
- spec/features/banks/show_spec.rb
- spec/models/bank_spec.rb
Changed to put User Story 7 method inside of bank model, instead of hard coding the method in html
Changed the html file
Added tests for bank model and features/banks/show_spec
> Change branches_count to be in bank model

- app/views/bank_branches/index.html.erb
- app/views/banks/index.html.erb
- app/views/banks/show.html.erb
- app/views/branches/show.html.erb
- config/routes.rb
- spec/features/banks/branches/index_spec.rb
- spec/features/banks/index_spec.rb
- spec/features/banks/show_spec.rb
- spec/features/branches/show_spec.rb
Added link to Branches index for all pages, except the actual Branches index
Added tests in each spec file, used `click_on` capybara successfully
> Add User Story 8 functionality and tests

- app/views/bank_branches/index.html.erb
- app/views/banks/show.html.erb
- app/views/branches/index.html.erb
- app/views/branches/show.html.erb
- spec/features/banks/branches/index_spec.rb
- spec/features/banks/show_spec.rb
- spec/features/branches/index_spec.rb
- spec/features/branches/show_spec.rb
Same as User Story 8
Added "Banks Main" link to every html file except "/banks"
Added test for every link
> Add functionality and tests for us9

- app/views/elevatorco_buildings/index.html.erb
- app/views/elevatorcos/index.html.erb
- app/views/elevatorcos/show.html.erb
- db/seeds.rb
- spec/features/buildings/index_spec.rb
- spec/features/buildings/show_spec.rb
- spec/features/elevatorcos/buildings/index_spec.rb
- spec/features/elevatorcos/index_spec.rb
- spec/features/elevatorcos/show_spec.rb
PR includes: 
Testing: 
- add click test for buildings main to all spec files
Views: 
- add link to buildings main to each view
DB seed: 
- add seed data for elevatorcos and buildings
> User story 8

- app/views/buildings/index.html.erb
- app/views/buildings/show.html.erb
- app/views/elevatorco_buildings/index.html.erb
- spec/features/buildings/index_spec.rb
- spec/features/buildings/show_spec.rb
- spec/features/elevatorcos/index_spec.rb
- spec/features/elevatorcos/show_spec.rb
PR includes: 
Tests: 
- link tests for elevatorcos index on each page
Views: 
- link to elevatorcos index on each page
> Pl user story 9

- app/views/banks/show.html.erb
- spec/features/banks/show_spec.rb
Added link in banks/show.html that will link to banks/:id/branches
Added test for link
> Add banks/show.html edits and test

- app/views/elevatorcos/show.html.erb
- spec/features/elevatorcos/show_spec.rb
PR includes: 
Test: 
- link test
View: 
- added link to elevatorco.id/buildings to elevatorcos show page
> Pl user story 10

- app/controllers/banks_controller.rb
- app/views/banks/index.html.erb
- app/views/banks/new.html.erb
- config/routes.rb
- spec/features/banks/new_spec.rb
- spec/features/banks/show_spec.rb
- Added #create method to bank controller
- added Create Bank button for bank#index
- added get and post routes for US11
- created new.html file with bank form
- added corresponding tests
> Add functionality for US11

- app/controllers/elevatorcos_controller.rb
- app/views/elevatorcos/index.html.erb
- app/views/elevatorcos/new.html.erb
- config/routes.rb
- spec/features/elevatorcos/new_spec.rb
This PR includes: 
Test files: 
- add test for new elevatorco link on index
- add test file for elevatorco_new page 
Routes: 
-add new and create routes 
Controllers: 
- add new, params, and create methods 
View: 
- add form to new page
> Feature: add create elevatorco functionality

- app/controllers/elevatorcos_controller.rb
- app/views/elevatorcos/edit.html.erb
- app/views/elevatorcos/show.html.erb
- config/routes.rb
- spec/features/elevatorcos/edit_spec.rb
PR Includes: 
Testing 
- add link test to elevatorcos show page spec
- add edit spec file with tests for update functionality 
Routes 
- added route to get edit and patch update 
Controllers 
- added methods for edit and update to elevatorco 
Views 
- added update link to elevatorcos show view
- created edit view form
> User Story 12

- app/controllers/bank_branches_controller.rb
- app/views/bank_branches/index.html.erb
- app/views/bank_branches/new.html.erb
- config/routes.rb
- spec/features/banks/branches/new_spec.rb
- Added params, new, and create methods to bank_branches_controller
- Put New Branch link in bank_branches index
- Added get/post routes for us13
- Created form for new branch
- Added corresponding tests
> Add us13 functionality

- app/controllers/branches_controller.rb
- app/views/branches/edit.html.erb
- app/views/branches/show.html.erb
- config/routes.rb
- spec/features/branches/edit_spec.rb
- Edit/Update methods in branches controller
- Added edit link to branches show page
- added routes (needs editing, had some merge conflicts and I hope I didn't screw up the file)
- created branches edit.html and edit_spec
> Finish user story 14

- app/controllers/branches_controller.rb
- app/models/bank.rb
- app/models/branch.rb
- spec/features/branches/index_spec.rb
- spec/models/branch_spec.rb
- Changed the branches#index to use a class method written in branches model
- Added that class method to branch model
- added test in branches/index_spec so make sure only branches where has_atm == true were showing
- Added tests in branch_spec for the class method
> Finish user story 15 I hope

- app/controllers/buildings_controller.rb
- app/controllers/elevatorcos_controller.rb
- app/models/building.rb
- app/models/elevatorco.rb
- spec/models/building_spec.rb
- spec/models/elevatorco_spec.rb
PR includes: 
- Model test for display_true method
- Fixed model test for sort_by method 
-display_true method in building model
-Fixed sort_by method in elevatorco model 
- Model methods added to controllers
> US 15 functionality and US 6 fixes

- app/controllers/elevatorco_buildings_controller.rb
- app/models/building.rb
- app/views/elevatorco_buildings/index.html.erb
- config/routes.rb
- spec/features/buildings/index_spec.rb
- spec/features/elevatorcos/buildings/index_spec.rb
- spec/models/building_spec.rb
PR includes: 
Tests: Model & feature tests for alphabetical sort functionality 
Routes: add route for alphabetical sort
Model: add method for alphabetical sort
Controller: add conditional block to index for alphabetical sort option
Views: add link for alphabetical sort option
Thinking this might need to be adjusted, since the URL doesn't land back at the index but will have to research
> Pl user story 16

- app/controllers/bank_branches_controller.rb
- app/views/bank_branches/index.html.erb
- config/routes.rb
- spec/features/banks/branches/index_spec.rb
- Edited bank_branches#index to include alphabetize param
- changed link_to link for alphabetize in index.html
- changed routes
- added corresponding tests
> finish user story 16

- app/controllers/elevatorco_buildings_controller.rb
- app/views/elevatorco_buildings/index.html.erb
- config/routes.rb
- spec/features/elevatorcos/buildings/index_spec.rb
> User Story 16 Refactor

- app/views/elevatorcos/index.html.erb
- spec/features/elevatorcos/index_spec.rb
PR includes: 
Parent index
- add edit link to each record 
Parent index spec
- add test for edit link
> Pl user story 17

- app/views/buildings/index.html.erb
- app/views/elevatorco_buildings/index.html.erb
- app/views/elevatorcos/index.html.erb
- spec/features/buildings/index_spec.rb
- spec/features/elevatorcos/buildings/index_spec.rb
- spec/features/elevatorcos/index_spec.rb
PR includes: 
Edit link tests for both buildings index spec and elevatorcos buildings index spec
Edit links added to each block for both buildings index and elevatorcos buildings index
> Pl user story 18

- app/controllers/elevatorcos_controller.rb
- app/models/elevatorco.rb
- app/views/elevatorcos/show.html.erb
- config/routes.rb
- spec/features/elevatorcos/show_spec.rb
PR includes: 
Test
- delete link and functionality test
Model 
- dependents destroy association 
Controller
- elevatorco destory method 
View
- elevatorco delete link
> Pl user story 19

- app/controllers/buildings_controller.rb
- app/views/buildings/show.html.erb
- config/routes.rb
- spec/features/buildings/show_spec.rb
PR includes: 
Building show test
- building delete 
Routes
- building delete route 
Controller
- building delete method 
View
- building delete link
> Pl user story 20

- app/controllers/branches_controller.rb
- app/views/branches/show.html.erb
- config/routes.rb
- spec/features/banks/show_spec.rb
- spec/features/branches/show_spec.rb
US20
Same as US 19 but in child show page
> Finish us20

- app/views/banks/index.html.erb
- app/views/branches/index.html.erb
- spec/features/banks/index_spec.rb
- spec/features/branches/index_spec.rb
Skipped US 21 for the time being
Added Delete buttons to parent and child indexes
Added routes to controller for #destroy
Added corresponding tests
> Finish functionality for both user stories

- app/controllers/elevatorco_buildings_controller.rb
- app/models/building.rb
- app/views/elevatorco_buildings/index.html.erb
- spec/features/elevatorcos/buildings/index_spec.rb
- spec/models/building_spec.rb
PR includes: 
tests: 
- model test and feature test
models: 
- add class method to filter buildings by num_units 
controller: 
- add conditional to index
view: 
- add form to submit num_units to filter by
> Pl user story 21

- app/controllers/bank_branches_controller.rb
- app/models/branch.rb
- app/views/bank_branches/index.html.erb
- spec/features/banks/branches/index_spec.rb
- spec/models/bank_spec.rb
- added another line to if/else statement in bank_branches#index
- added class method to branch model
- put new form into bank_branches/index.html
- Added corresponding tests for model_spec and index_spec
> Finish user story 21

- app/controllers/elevatorco_buildings_controller.rb
- app/views/elevatorco_buildings/index.html.erb
PR includes: 
- mini refactor for US 21 per our project check-in learnings!
> US 21 refactor

- Gemfile
- Gemfile.lock
- app/controllers/elevatorco_buildings_controller.rb
- app/controllers/elevatorcos_controller.rb
- spec/features/elevatorcos/buildings/index_spec.rb
- spec/features/elevatorcos/index_spec.rb
PR includes: 
orderly gem added to gemfile 
tests: 
added tests for ordered methods using orderly gem
controller: 
added validations to create and update methods
> Orderly gem

- app/controllers/bank_branches_controller.rb
- app/models/bank.rb
- app/models/branch.rb
- app/views/banks/edit.html.erb
- app/views/branches/edit.html.erb
- spec/features/banks/edit_spec.rb
- spec/features/banks/index_spec.rb
- spec/features/branches/edit_spec.rb
- spec/features/branches/index_spec.rb
- spec/models/bank_spec.rb
- spec/models/branch_spec.rb
- Added more testing for better coverage in models
- Added more testing for html files/routes/paths
> Fortify testing

- app/assets/stylesheets/main.css
- app/views/buildings/edit.html.erb
- app/views/buildings/index.html.erb
- app/views/buildings/show.html.erb
- app/views/elevatorco_buildings/index.html.erb
- app/views/elevatorco_buildings/new.html.erb
- app/views/elevatorcos/edit.html.erb
- app/views/elevatorcos/index.html.erb
- app/views/elevatorcos/new.html.erb
- app/views/elevatorcos/show.html.erb
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
- db/schema.rb
- db/seeds.rb
- spec/features/buildings/edit_spec.rb
- spec/features/buildings/index_spec.rb
- spec/features/buildings/show_spec.rb
- spec/features/elevatorcos/buildings/index_spec.rb
- spec/features/elevatorcos/buildings/new_spec.rb
- spec/features/elevatorcos/edit_spec.rb
- spec/features/elevatorcos/index_spec.rb
- spec/features/elevatorcos/new_spec.rb
- spec/features/elevatorcos/show_spec.rb
PR includes: 
- navbar added to all views
- feature test navbar links for all views
- css stylesheet
- form fixes to rule out edgecases
- feature tests adjusted to interact with forms
> Pl refactor
